### ISSUE TITLE
install-local.py is failing with `DistributionNotFound: No distributions at all found for wheel`

### ISSUE THREAD

**Issue by lukas-b** [pre-commit/pre-commit.github.io#52]
Non Administrative Installation (`curl http://pre-commit.com/install-local.py | python` via http://pre-commit.com/#install) is failing with `DistributionNotFound: No distributions at all found for wheel`:

```python
No distributions at all found for wheel
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/virtualenv_support/pip-1.5.5-py2.py3-none-any.whl/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/virtualenv_support/pip-1.5.5-py2.py3-none-any.whl/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.6/dist-packages/virtualenv_support/pip-1.5.5-py2.py3-none-any.whl/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.6/dist-packages/virtualenv_support/pip-1.5.5-py2.py3-none-any.whl/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for wheel
```

Looks like virtualenv issue.

**Comment by asottile** [comment]
This in fact fails even harder in an empty docker container:

```
root@042dbf41e80c:/build# curl http://pre-commit.com/install-local.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   98k  100   98k    0     0   242k      0 --:--:-- --:--:-- --:--:--  303k
New python executable in /root/.pre-commit-venv/bin/python
Cannot find a wheel for setuptools
Cannot find a wheel for pip
Installing setuptools, pip, wheel...
  Complete output from command /root/.pre-commit-venv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pip
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "<stdin>", line 2402, in <module>
  File "<stdin>", line 834, in main
  File "<stdin>", line 1006, in create_environment
  File "<stdin>", line 971, in install_wheel
  File "<stdin>", line 912, in call_subprocess
OSError: Command /root/.pre-commit-venv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
```

Might be time to consider a different approach for this...
